# Generated by Django 5.2.3 on 2025-07-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_fraud_prob_transaction_is_anomaly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(choices=[('MyBankBackend', 'MyBankBackend')], default='MyBankBackend', max_length=100),
        ),
    ]
