# Generated by Django 5.2.3 on 2025-07-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_ip_address_transaction_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
